CREATE TABLE Users (
    Id INT AUTO_INCREMENT NOT NULL,
    UserName VARCHAR(128) NOT NULL UNIQUE,
    Email VARCHAR(256),
    EmailConfirmed BOOLEAN NOT NULL,
    PasswordHash VARCHAR(128) NOT NULL,
    Registered DATETIME NOT NULL,
    SecurityStamp VARCHAR(128),
    PhoneNumber VARCHAR(40),
    PhoneNumberConfirmed TINYINT(1) NOT NULL,
    TwoFactorEnabled BOOLEAN NOT NULL,
    LockoutEndDateUtc DATETIME,
    LockoutEnabled BOOLEAN NOT NULL,
    AccessFailedCount INT NOT NULL,
    LastLoginInWeb DATETIME,
    LastLoginInApp DATETIME,
    LastSynchronization DATETIME,
    SecurityLevel TINYINT(2) NOT NULL,
    Description VARCHAR(40),
    Activated BOOLEAN NOT NULL,
PRIMARY KEY(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE UserRoles (
    UserId INT NOT NULL,
    RoleId INT NOT NULL,
PRIMARY KEY(UserId, RoleId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Roles (
    Id INT AUTO_INCREMENT NOT NULL,
    Description LONGTEXT,
    Name VARCHAR(128) NOT NULL,
PRIMARY KEY(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE UserLogins (
    LoginProvider INT NOT NULL,
    ProviderKey INT NOT NULL,
    UserId INT NOT NULL,
PRIMARY KEY(LoginProvider, ProviderKey, UserId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE UserClaims (
    Id INT AUTO_INCREMENT NOT NULL,
    UserId INT NOT NULL,
    ClaimType LONGTEXT,
    ClaimValue LONGTEXT,
PRIMARY KEY(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Messages (
    Id INT AUTO_INCREMENT NOT NULL,
    SendDate DATETIME NOT NULL,
    ReceiveDate DATETIME,
    Displayed BOOLEAN NOT NULL,
    Conversation INT NOT NULL,
    Content TEXT NOT NULL,
    SecurityLevel TINYINT(2) NOT NULL,
    ReceiverPublicKey INT NOT NULL,
    SenderPublicKey INT NOT NULL,
    Visible BOOLEAN NOT NULL,
PRIMARY KEY(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PublicKeys (
    Id INT AUTO_INCREMENT NOT NULL,
    Owner INT NOT NULL,
    CreateDate DATETIME NOT NULL,
    DisableDate DATETIME,
    KeyString TEXT NOT NULL,
PRIMARY KEY(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Conversations (
    Id INT AUTO_INCREMENT NOT NULL,
    Sender INT NOT NULL,
    Receiver INT NOT NULL,
PRIMARY KEY(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE BlockedUsers (
    Id INT AUTO_INCREMENT NOT NULL,
    User INT NOT NULL,
    Blocked INT NOT NULL,
    BlockDate DATE NOT NULL,
PRIMARY KEY(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Contacts (
    Id INT AUTO_INCREMENT NOT NULL,
    Owner INT NOT NULL,
    ContactUser INT NOT NULL,
    Accepted BOOLEAN NOT NULL,
    InviteDate DATETIME NOT NULL,
    Enabled BOOLEAN NOT NULL,
PRIMARY KEY(Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE UserRoles ADD CONSTRAINT UserRolesUserId_UsersId FOREIGN KEY(UserId) REFERENCES Users (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE UserRoles ADD CONSTRAINT UserRolesRoleId_RolesId FOREIGN KEY(RoleId) REFERENCES Roles (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE UserLogins ADD CONSTRAINT UserLoginsUserId_UsersId FOREIGN KEY(UserId) REFERENCES Users (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE UserClaims ADD CONSTRAINT UserClaimsUserId_UsersId FOREIGN KEY(UserId) REFERENCES Users (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Messages ADD CONSTRAINT MessagesConversation_ConversationsId FOREIGN KEY(Conversation) REFERENCES Conversations (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Messages ADD CONSTRAINT MessagesReceiverPublicKey_PublicKeysId FOREIGN KEY(ReceiverPublicKey) REFERENCES PublicKeys (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Messages ADD CONSTRAINT MessagesSenderPublicKey_PublicKeysId FOREIGN KEY(SenderPublicKey) REFERENCES PublicKeys (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE PublicKeys ADD CONSTRAINT PublicKeysOwner_UsersId FOREIGN KEY(Owner) REFERENCES Users (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Conversations ADD CONSTRAINT ConversationsSender_UsersId FOREIGN KEY(Sender) REFERENCES Users (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Conversations ADD CONSTRAINT ConversationsReceiver_UsersId FOREIGN KEY(Receiver) REFERENCES Users (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BlockedUsers ADD CONSTRAINT BlockedUsersUser_UsersId FOREIGN KEY(User) REFERENCES Users (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE BlockedUsers ADD CONSTRAINT BlockedUsersBlocked_UsersId FOREIGN KEY(Blocked) REFERENCES Users (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Contacts ADD CONSTRAINT ContactsOwner_UsersId FOREIGN KEY(Owner) REFERENCES Users (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE Contacts ADD CONSTRAINT ContactsContactUser_UsersId FOREIGN KEY(ContactUser) REFERENCES Users (Id) ON DELETE NO ACTION ON UPDATE NO ACTION;

